In [1]:
import pandas as pd
from collections import Counter

In [2]:
filepath = "Resources/dirty_Tableau_pre_covid_sentiments_predictions_headlines_lr_model.csv"
df = pd.read_csv(filepath)

In [3]:
# df.columns
df.drop(["Unnamed: 0"], axis = 1, inplace = True)
df

     predicted_label                                               text
0            Neutral  Stitch Fix, Inc. (SFIX) CEO Katrina Lake on Q4...
1            Neutral  Goldman Sachs reshuffles Asia M&A leadership a...
2           Positive  What We Learned From Amazon's Big Hardware Ann...
3           Positive  Cerner: A Great Stock To Add To Your Portfolio...
4            Neutral  Johnson & Johnson settles Ohio lawsuits to avo...
...              ...                                                ...
9145        Positive  This mobile WiFi company is seeing a huge dema...
9146         Neutral  Fox Selling $1.2 Billion In Debt, Follows Disn...
9147         Neutral                        Air Canada: The Long Runway
9148        Negative  ProPetro Holding (PUMP) Q4 Earnings and Revenu...
9149        Negative  Xerox drops $34B HP take-over bid amid COVID-1...

[9150 rows x 2 columns]

In [4]:
filepath2 = "Resources/precovid_articles_dates.csv"
df1 = pd.read_csv(filepath2, header=None)
df2 = df1.rename(columns={0:"text", 1:"date"})
df2

                                                   text       date
0     Stitch Fix, Inc. (SFIX) CEO Katrina Lake on Q4...  10/1/2019
1     Goldman Sachs reshuffles Asia M&A leadership a...  10/1/2019
2     What We Learned From Amazon's Big Hardware Ann...  10/1/2019
3     Cerner: A Great Stock To Add To Your Portfolio...  10/1/2019
4     Johnson & Johnson settles Ohio lawsuits to avo...  10/1/2019
...                                                 ...        ...
9145  This mobile WiFi company is seeing a huge dema...  3/31/2020
9146  Fox Selling $1.2 Billion In Debt, Follows Disn...  3/31/2020
9147                        Air Canada: The Long Runway  3/31/2020
9148  ProPetro Holding (PUMP) Q4 Earnings and Revenu...  3/31/2020
9149  Xerox drops $34B HP take-over bid amid COVID-1...  3/31/2020

[9150 rows x 2 columns]

In [5]:
merged_df = pd.merge(df, df2, on="text", how="inner")
merged_df

,predicted_label,text,date
0,Neutral,"Stitch Fix, Inc. (SFIX) CEO Katrina Lake on Q4...",10/1/2019
1,Neutral,Goldman Sachs reshuffles Asia M&A leadership a...,10/1/2019
2,Positive,What We Learned From Amazon's Big Hardware Ann...,10/1/2019
3,Positive,Cerner: A Great Stock To Add To Your Portfolio...,10/1/2019
4,Neutral,Johnson & Johnson settles Ohio lawsuits to avo...,10/1/2019
...,...,...,...
9125,Positive,This mobile WiFi company is seeing a huge dema...,3/31/2020
9126,Neutral,"Fox Selling $1.2 Billion In Debt, Follows Disn...",3/31/2020
9127,Neutral,Air Canada: The Long Runway,3/31/2020
9128,Negative,ProPetro Holding (PUMP) Q4 Earnings and Revenu...,3/31/2020
9129,Negative,Xerox drops $34B HP take-over bid amid COVID-1...,3/31/2020

In [6]:
def convert(lst):
    return lst.split()

In [7]:
merged_df["text_list"] = merged_df.apply(lambda row: convert(row["text"]), axis=1)
merged_df

,predicted_label,text,date,text_list
0,Neutral,"Stitch Fix, Inc. (SFIX) CEO Katrina Lake on Q4...",10/1/2019,"[Stitch, Fix,, Inc., (SFIX), CEO, Katrina, Lak..."
1,Neutral,Goldman Sachs reshuffles Asia M&A leadership a...,10/1/2019,"[Goldman, Sachs, reshuffles, Asia, M&A, leader..."
2,Positive,What We Learned From Amazon's Big Hardware Ann...,10/1/2019,"[What, We, Learned, From, Amazon's, Big, Hardw..."
3,Positive,Cerner: A Great Stock To Add To Your Portfolio...,10/1/2019,"[Cerner:, A, Great, Stock, To, Add, To, Your, ..."
4,Neutral,Johnson & Johnson settles Ohio lawsuits to avo...,10/1/2019,"[Johnson, &, Johnson, settles, Ohio, lawsuits,..."
...,...,...,...,...
9125,Positive,This mobile WiFi company is seeing a huge dema...,3/31/2020,"[This, mobile, WiFi, company, is, seeing, a, h..."
9126,Neutral,"Fox Selling $1.2 Billion In Debt, Follows Disn...",3/31/2020,"[Fox, Selling, $1.2, Billion, In, Debt,, Follo..."
9127,Neutral,Air Canada: The Long Runway,3/31/2020,"[Air, Canada:, The, Long, Runway]"
9128,Negative,ProPetro Holding (PUMP) Q4 Earnings and Revenu...,3/31/2020,"[ProPetro, Holding, (PUMP), Q4, Earnings, and,..."
9129,Negative,Xerox drops $34B HP take-over bid amid COVID-1...,3/31/2020,"[Xerox, drops, $34B, HP, take-over, bid, amid,..."

In [8]:
df_textlist = merged_df[["predicted_label", "date", "text_list"]]
df_textlist

,predicted_label,date,text_list
0,Neutral,10/1/2019,"[Stitch, Fix,, Inc., (SFIX), CEO, Katrina, Lak..."
1,Neutral,10/1/2019,"[Goldman, Sachs, reshuffles, Asia, M&A, leader..."
2,Positive,10/1/2019,"[What, We, Learned, From, Amazon's, Big, Hardw..."
3,Positive,10/1/2019,"[Cerner:, A, Great, Stock, To, Add, To, Your, ..."
4,Neutral,10/1/2019,"[Johnson, &, Johnson, settles, Ohio, lawsuits,..."
...,...,...,...
9125,Positive,3/31/2020,"[This, mobile, WiFi, company, is, seeing, a, h..."
9126,Neutral,3/31/2020,"[Fox, Selling, $1.2, Billion, In, Debt,, Follo..."
9127,Neutral,3/31/2020,"[Air, Canada:, The, Long, Runway]"
9128,Negative,3/31/2020,"[ProPetro, Holding, (PUMP), Q4, Earnings, and,..."
9129,Negative,3/31/2020,"[Xerox, drops, $34B, HP, take-over, bid, amid,..."

In [9]:
out = []
for index, row in df_textlist.iterrows():
    for item in row["text_list"]:
        row["keywords"] = item
        out += [row.copy()]
        
flattened_df = pd.DataFrame(out)
flattened_df

,predicted_label,date,text_list,keywords
0,Neutral,10/1/2019,"[Stitch, Fix,, Inc., (SFIX), CEO, Katrina, Lak...",Stitch
0,Neutral,10/1/2019,"[Stitch, Fix,, Inc., (SFIX), CEO, Katrina, Lak...","Fix,"
0,Neutral,10/1/2019,"[Stitch, Fix,, Inc., (SFIX), CEO, Katrina, Lak...",Inc.
0,Neutral,10/1/2019,"[Stitch, Fix,, Inc., (SFIX), CEO, Katrina, Lak...",(SFIX)
0,Neutral,10/1/2019,"[Stitch, Fix,, Inc., (SFIX), CEO, Katrina, Lak...",CEO
...,...,...,...,...
9129,Negative,3/31/2020,"[Xerox, drops, $34B, HP, take-over, bid, amid,...",take-over
9129,Negative,3/31/2020,"[Xerox, drops, $34B, HP, take-over, bid, amid,...",bid
9129,Negative,3/31/2020,"[Xerox, drops, $34B, HP, take-over, bid, amid,...",amid
9129,Negative,3/31/2020,"[Xerox, drops, $34B, HP, take-over, bid, amid,...",COVID-19
9129,Negative,3/31/2020,"[Xerox, drops, $34B, HP, take-over, bid, amid,...",uncertainty

In [10]:
flattened_df1 = flattened_df.drop("text_list", axis=1)
flattened_df1

     predicted_label       date     keywords
0            Neutral  10/1/2019       Stitch
0            Neutral  10/1/2019         Fix,
0            Neutral  10/1/2019         Inc.
0            Neutral  10/1/2019       (SFIX)
0            Neutral  10/1/2019          CEO
...              ...        ...          ...
9129        Negative  3/31/2020    take-over
9129        Negative  3/31/2020          bid
9129        Negative  3/31/2020         amid
9129        Negative  3/31/2020     COVID-19
9129        Negative  3/31/2020  uncertainty

[99883 rows x 3 columns]

In [21]:
# Removing Numeric Values from Keywords
flattened_df2 = flattened_df1[~flattened_df1["keywords"].str.contains("^\d+$")]
flattened_df2

     predicted_label       date     keywords
0            Neutral  10/1/2019       Stitch
0            Neutral  10/1/2019         Fix,
0            Neutral  10/1/2019         Inc.
0            Neutral  10/1/2019       (SFIX)
0            Neutral  10/1/2019          CEO
...              ...        ...          ...
9129        Negative  3/31/2020    take-over
9129        Negative  3/31/2020          bid
9129        Negative  3/31/2020         amid
9129        Negative  3/31/2020     COVID-19
9129        Negative  3/31/2020  uncertainty

[96564 rows x 3 columns]

In [30]:
# Cleaning text with symbols
import re
flattened_df2["keywords_clean"] = flattened_df2["keywords"].map(lambda x: re.sub(r'\W+', '', x))

/Users/abayomi/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [32]:
flattened_df3 = flattened_df2[["predicted_label", "date", "keywords_clean"]]
flattened_df3

     predicted_label       date keywords_clean
0            Neutral  10/1/2019         Stitch
0            Neutral  10/1/2019            Fix
0            Neutral  10/1/2019            Inc
0            Neutral  10/1/2019           SFIX
0            Neutral  10/1/2019            CEO
...              ...        ...            ...
9129        Negative  3/31/2020       takeover
9129        Negative  3/31/2020            bid
9129        Negative  3/31/2020           amid
9129        Negative  3/31/2020        COVID19
9129        Negative  3/31/2020    uncertainty

[96564 rows x 3 columns]

In [39]:
# Check for empty rows
import numpy as np
np.where(pd.isnull(flattened_df3))

(array([], dtype=int64), array([], dtype=int64))

In [49]:
# Filter out negative sentiment
neg_df = flattened_df3.loc[flattened_df3["predicted_label"] == "Negative"]
neg_df

     predicted_label       date keywords_clean
27          Negative  10/1/2019        Walmart
27          Negative  10/1/2019    Considering
27          Negative  10/1/2019            Its
27          Negative  10/1/2019        Options
27          Negative  10/1/2019            for
...              ...        ...            ...
9129        Negative  3/31/2020       takeover
9129        Negative  3/31/2020            bid
9129        Negative  3/31/2020           amid
9129        Negative  3/31/2020        COVID19
9129        Negative  3/31/2020    uncertainty

[4913 rows x 3 columns]

In [52]:
x = neg_df["keywords_clean"].value_counts().to_frame()
x

              keywords_clean
Why                      121
Earnings                 119
Down                     108
Last                     100
Report                    93
...                      ...
Pullback                   1
muted                      1
Level                      1
Dramatically               1
Cash                       1

[1979 rows x 1 columns]

In [ ]:
# Neutral_Text = ""
# Pos_Text = ""
# Neg_Text = ""
# for index, row in merged_df.iterrows():
# #     print(row['predicted_label'])
#     if row['predicted_label'] == "Neutral":
#         Neutral_Text = Neutral_Text+row['text']+' '
#     if row['predicted_label'] == "Positive":
#         Pos_Text = Pos_Text+row['text']+' '
#     if row['predicted_label'] == "Negative":
#         Neg_Text = Neg_Text+row['text']+' '

In [ ]:
# Neutral_Text

In [ ]:
# # Cleaning text and lower casing all words
# for char in ',$()-?&\'.‘’%:':
#     Neutral_Text=Neutral_Text.replace(char,' ')
# Neutral_Text
# Neutral_Text = Neutral_Text.lower()
# # split returns a list of words delimited by sequences of whitespace (including tabs, newlines, etc, like re's \s) 
# word_list_neutral = Neutral_Text.split()
# neutral_common_words = Counter(word_list_neutral).most_common()
# df_sentiment_neutral = pd.DataFrame(neutral_common_words)
# df_sentiment_neutral['predicted_labels'] = "Neutral"
# # neutral_common_words

In [ ]:
# # Cleaning text and lower casing all words
# for char in ',$()-?&\'.‘’%:':
#     Pos_Text=Pos_Text.replace(char,' ')
# Pos_Text = Pos_Text.lower()
# # split returns a list of words delimited by sequences of whitespace (including tabs, newlines, etc, like re's \s) 
# word_list_Pos = Pos_Text.split()
# pos_common_words = Counter(word_list_Pos).most_common()
# df_sentiment_pos = pd.DataFrame(pos_common_words)
# df_sentiment_pos['predicted_labels'] = "Positive"
# df_sentiment_pos

In [ ]:
# # Cleaning text and lower casing all words
# for char in ',$()-?&\'.‘’%:':
#     Neg_Text=Pos_Text.replace(char,' ')
# Neg_Text = Neg_Text.lower()
# # split returns a list of words delimited by sequences of whitespace (including tabs, newlines, etc, like re's \s) 
# word_list_Neg = Neg_Text.split()
# neg_common_words = Counter(word_list_Neg).most_common()
# df_sentiment_neg = pd.DataFrame(neg_common_words)
# df_sentiment_neg['predicted_labels'] = "Negative"
# df_sentiment_neg

In [ ]:
# df_sentiment_all = df_sentiment_pos.append(df_sentiment_neg)
# df_sentiment_all = df_sentiment_all.append(df_sentiment_neutral)
# df_sentiment_all

In [ ]:
# df1 = pd.DataFrame(common_words)

In [ ]:
# df_sentiment_all.to_csv("Resources/Tableau_pre_covid_word_count_with_sentiment.csv")