In [1]:
import pandas as pd

In [2]:
filepath = "Resources/PREDICTIONS_covid_peak_to_slowdown_lr_model.csv"
df = pd.read_csv(filepath)
df.head()

,Unnamed: 0,predicted_label,text,words
0,0,Positive,Moderna Coronavirus Vaccine Clinical Trials Ar...,"['moderna', 'coronavirus', 'vaccine', 'clinica..."
1,1,Positive,Tesla could help make lithium ion batteries fo...,"['tesla', 'could', 'help', 'make', 'lithium', ..."
2,2,Negative,Chinese Airlines See Short-Term Virus Hit,"['chinese', 'airlines', 'see', 'short-term', '..."
3,3,Negative,Why MercadoLibre Stock Lost 21% Last Month,"['why', 'mercadolibre', 'stock', 'lost', '21%'..."
4,4,Positive,Cruise operator Carnival pays high price to ge...,"['cruise', 'operator', 'carnival', 'pays', 'hi..."

In [3]:
df.drop(["Unnamed: 0", "words"], axis=1, inplace=True)
df.head()

  predicted_label                                               text
0        Positive  Moderna Coronavirus Vaccine Clinical Trials Ar...
1        Positive  Tesla could help make lithium ion batteries fo...
2        Negative          Chinese Airlines See Short-Term Virus Hit
3        Negative         Why MercadoLibre Stock Lost 21% Last Month
4        Positive  Cruise operator Carnival pays high price to ge...

In [4]:
# Function for splitting text column into list of words
def convert(lst):
    return lst.split()

In [5]:
# Applying function to text row
df["words"] = df.apply(lambda row: convert(row["text"]), axis=1)
df.head()

,predicted_label,text,words
0,Positive,Moderna Coronavirus Vaccine Clinical Trials Ar...,"[Moderna, Coronavirus, Vaccine, Clinical, Tria..."
1,Positive,Tesla could help make lithium ion batteries fo...,"[Tesla, could, help, make, lithium, ion, batte..."
2,Negative,Chinese Airlines See Short-Term Virus Hit,"[Chinese, Airlines, See, Short-Term, Virus, Hit]"
3,Negative,Why MercadoLibre Stock Lost 21% Last Month,"[Why, MercadoLibre, Stock, Lost, 21%, Last, Mo..."
4,Positive,Cruise operator Carnival pays high price to ge...,"[Cruise, operator, Carnival, pays, high, price..."

In [6]:
filepath2 = "Resources/covid_peak_to_slow_down_articles_dates.csv"
df1 = pd.read_csv(filepath2, header=None)
df2 = df1.rename(columns={0:"text", 1:"date"})
df2.head()

                                                text        date
0  Moderna Coronavirus Vaccine Clinical Trials Ar...  04/01/2020
1  Tesla could help make lithium ion batteries fo...  04/01/2020
2          Chinese Airlines See Short-Term Virus Hit  04/01/2020
3         Why MercadoLibre Stock Lost 21% Last Month  04/01/2020
4  Cruise operator Carnival pays high price to ge...  04/01/2020

In [7]:
merged_df = pd.merge(df, df2, on="text", how="inner")
merged_df

,predicted_label,text,words,date
0,Positive,Moderna Coronavirus Vaccine Clinical Trials Ar...,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",04/01/2020
1,Positive,Tesla could help make lithium ion batteries fo...,"[Tesla, could, help, make, lithium, ion, batte...",04/01/2020
2,Negative,Chinese Airlines See Short-Term Virus Hit,"[Chinese, Airlines, See, Short-Term, Virus, Hit]",04/01/2020
3,Negative,Why MercadoLibre Stock Lost 21% Last Month,"[Why, MercadoLibre, Stock, Lost, 21%, Last, Mo...",04/01/2020
4,Positive,Cruise operator Carnival pays high price to ge...,"[Cruise, operator, Carnival, pays, high, price...",04/01/2020
...,...,...,...,...
6083,Neutral,Nikola To Participate In Upcoming Investor Con...,"[Nikola, To, Participate, In, Upcoming, Invest...",07/31/2020
6084,Negative,"Spirit AeroSystems cuts 1,100 jobs due to coro...","[Spirit, AeroSystems, cuts, 1,100, jobs, due, ...",07/31/2020
6085,Positive,First Midwest Bancorp: Sharp Earnings Recovery...,"[First, Midwest, Bancorp:, Sharp, Earnings, Re...",07/31/2020
6086,Neutral,"The Bancorp, Inc. (TBBK) CEO Damian Kozlowski ...","[The, Bancorp,, Inc., (TBBK), CEO, Damian, Koz...",07/31/2020
6087,Neutral,Balchem Corporation (BCPC) CEO Ted Harris on Q...,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",07/31/2020

In [8]:
# Rearranging columns
df_wordslist = merged_df[["predicted_label", "date", "words"]]
df_wordslist.head()

,predicted_label,date,words
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria..."
1,Positive,04/01/2020,"[Tesla, could, help, make, lithium, ion, batte..."
2,Negative,04/01/2020,"[Chinese, Airlines, See, Short-Term, Virus, Hit]"
3,Negative,04/01/2020,"[Why, MercadoLibre, Stock, Lost, 21%, Last, Mo..."
4,Positive,04/01/2020,"[Cruise, operator, Carnival, pays, high, price..."

In [9]:
# Splitting words list into individual words
out = []
for index, row in df_wordslist.iterrows():
    for item in row["words"]:
        row["keywords"] = item
        out += [row.copy()]
        
flattened_df = pd.DataFrame(out)
flattened_df

,predicted_label,date,words,keywords
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",Moderna
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",Coronavirus
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",Vaccine
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",Clinical
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",Trials
...,...,...,...,...
6087,Neutral,07/31/2020,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",Results
6087,Neutral,07/31/2020,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",-
6087,Neutral,07/31/2020,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",Earnings
6087,Neutral,07/31/2020,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",Call
6087,Neutral,07/31/2020,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",Transcript

In [10]:
# Removing Numeric Values from Keywords
flattened_df1 = flattened_df[~flattened_df["keywords"].str.contains("^\d+$")]
flattened_df1

,predicted_label,date,words,keywords
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",Moderna
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",Coronavirus
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",Vaccine
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",Clinical
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",Trials
...,...,...,...,...
6087,Neutral,07/31/2020,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",Results
6087,Neutral,07/31/2020,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",-
6087,Neutral,07/31/2020,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",Earnings
6087,Neutral,07/31/2020,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",Call
6087,Neutral,07/31/2020,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",Transcript

In [11]:
# Cleaning text with symbols
import re
flattened_df1["keywords_clean"] = flattened_df1["keywords"].map(lambda x: re.sub(r'\W+', '', x))
flattened_df1

<ipython-input-11-efda97dabf03>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  flattened_df1["keywords_clean"] = flattened_df1["keywords"].map(lambda x: re.sub(r'\W+', '', x))

,predicted_label,date,words,keywords,keywords_clean
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",Moderna,Moderna
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",Coronavirus,Coronavirus
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",Vaccine,Vaccine
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",Clinical,Clinical
0,Positive,04/01/2020,"[Moderna, Coronavirus, Vaccine, Clinical, Tria...",Trials,Trials
...,...,...,...,...,...
6087,Neutral,07/31/2020,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",Results,Results
6087,Neutral,07/31/2020,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",-,
6087,Neutral,07/31/2020,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",Earnings,Earnings
6087,Neutral,07/31/2020,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",Call,Call
6087,Neutral,07/31/2020,"[Balchem, Corporation, (BCPC), CEO, Ted, Harri...",Transcript,Transcript

In [12]:
# Check for empty rows
import numpy as np
np.where(pd.isnull(flattened_df1))

(array([], dtype=int64), array([], dtype=int64))

In [14]:
filepath3 = "Resources/Tickers_Nested_covid_peak_to_slow_down_.csv"
df_tickers = pd.read_csv(filepath3, header=None)
df_tickers1 = df_tickers.rename(columns={0:"tickers", 1:"text", 2:"ticker_counts"})
df_tickers1

,tickers,text,ticker_counts
0,KRA,Kraton Corporation (KRA) CEO Kevin Fogarty on ...,1
1,CRS,Carpenter Technology Corporation (CRS) CEO Ton...,1
2,MAT,Mattel Mourns the Passing of Former Chairman a...,1
3,SCTBF,Securitas AB (SCTBF) CEO Magnus Ahlqvist on Q2...,1
4,"CERN , MO",Stocks This Week: Sell Short Altria And Cerner,2
...,...,...,...
6095,RCI,Carvana CEO says company has more than tripled...,1
6096,DT,JPMorgan Bonuses Set for 20% Jump,1
6097,VFC,Corning Incorporated (GLW) Management Presents...,1
6098,OII,"SandRidge Energy, Inc. Announces Closing of Ne...",1
6099,VOPKY,Tower One Announces Third Quarter 2020 Results...,1

In [15]:
filepath4 = "Resources/stock_list_tableau.csv"
df_stocklist = pd.read_csv(filepath4)
df_stocklist

,Exchange,Symbol,Name,Country,Sector,Industry
0,NASDAQ,AADI,Aadi Bioscience Inc. Common Stock,United States,Health Care,Biotechnology: Pharmaceutical Preparations
1,NASDAQ,AAL,American Airlines Group Inc. Common Stock,United States,Transportation,Air Freight/Delivery Services
2,NASDAQ,AAME,Atlantic American Corporation Common Stock,United States,Finance,Life Insurance
3,NASDAQ,AAOI,Applied Optoelectronics Inc. Common Stock,United States,Technology,Semiconductors
4,NASDAQ,AAON,AAON Inc. Common Stock,United States,Capital Goods,Industrial Machinery/Components
...,...,...,...,...,...,...
5384,AMEX,WWR,Westwater Resources Inc. Common Stock,United States,Basic Industries,Other Metals and Minerals
5385,AMEX,WYY,WidePoint Corporation Common Stock,United States,Technology,EDP Services
5386,AMEX,XPL,Solitario Zinc Corp. Common Stock,United States,Basic Industries,Metal Mining
5387,AMEX,XTNT,Xtant Medical Holdings Inc. Common Stock,United States,Health Care,Medical Specialities
5388,AMEX,YCBD,cbdMD Inc. Common Stock,United States,Health Care,Biotechnology: Pharmaceutical Preparations

In [16]:
df_stocklist1 = df_stocklist.rename(columns={"Symbol":"tickers"})
df_stocklist1.head()

,Exchange,tickers,Name,Country,Sector,Industry
0,NASDAQ,AADI,Aadi Bioscience Inc. Common Stock,United States,Health Care,Biotechnology: Pharmaceutical Preparations
1,NASDAQ,AAL,American Airlines Group Inc. Common Stock,United States,Transportation,Air Freight/Delivery Services
2,NASDAQ,AAME,Atlantic American Corporation Common Stock,United States,Finance,Life Insurance
3,NASDAQ,AAOI,Applied Optoelectronics Inc. Common Stock,United States,Technology,Semiconductors
4,NASDAQ,AAON,AAON Inc. Common Stock,United States,Capital Goods,Industrial Machinery/Components

In [17]:
df_merged_tickers = pd.merge(df_stocklist1, df_tickers1, on="tickers")
df_merged_tickers

,Exchange,tickers,Name,Country,Sector,Industry,text,ticker_counts
0,NASDAQ,ALTM,Altus Midstream Company Class A Common Stock,United States,Energy,Oil & Gas Production,Altus Midstream Company (ALTM) CEO Clay Bretch...,1
1,NASDAQ,ALTM,Altus Midstream Company Class A Common Stock,United States,Energy,Oil & Gas Production,Microsoft Hopes To Clinch TikTok Acquisition B...,1
2,NASDAQ,ALTM,Altus Midstream Company Class A Common Stock,United States,Energy,Oil & Gas Production,"National CineMedia, Inc. (NCMI) CEO Tom Lesins...",1
3,NASDAQ,ALTM,Altus Midstream Company Class A Common Stock,United States,Energy,Oil & Gas Production,FIRSTENERGY SHAREHOLDER ALERT by Former Louisi...,1
4,NASDAQ,ALTM,Altus Midstream Company Class A Common Stock,United States,Energy,Oil & Gas Production,Torex Gold Resources Inc. (TORXF) CEO Jody Kuz...,1
...,...,...,...,...,...,...,...,...
4509,NYSE,VFC,V.F. Corporation Common Stock,United States,Consumer Non-Durables,Apparel,"Is GEE Group, Inc. (JOB) A Good Stock To Buy?",1
4510,NYSE,VFC,V.F. Corporation Common Stock,United States,Consumer Non-Durables,Apparel,Here is What Hedge Funds Think About PolyMet M...,1
4511,NYSE,VFC,V.F. Corporation Common Stock,United States,Consumer Non-Durables,Apparel,This Could Be the Next Oil Stock to Go Bankrupt,1
4512,NYSE,VFC,V.F. Corporation Common Stock,United States,Consumer Non-Durables,Apparel,Amplify Online Retail ETF: Long Time Coming,1
4513,NYSE,VFC,V.F. Corporation Common Stock,United States,Consumer Non-Durables,Apparel,Corning Incorporated (GLW) Management Presents...,1

In [18]:
df_merged_x = pd.merge(df_merged_tickers, merged_df, on="text")
df_merged_x

Empty DataFrame
Columns: [Exchange, tickers, Name, Country, Sector, Industry, text, ticker_counts, predicted_label, words, date]
Index: []

In [27]:
merged_df.dtypes

predicted_label    object
text               object
words              object
date               object
dtype: object

In [25]:
df_merged_tickers.dtypes

Exchange         object
tickers          object
Name             object
Country          object
Sector           object
Industry         object
text             object
ticker_counts     int64
dtype: object

In [21]:
# Splitting words list into individual words
out1 = []
for index, row in df_merged_x.iterrows():
    for item in row["words"]:
        row["keywords"] = item
        out1 += [row.copy()]
        
flattened_df_ = pd.DataFrame(out1)
flattened_df_

Empty DataFrame
Columns: []
Index: []

In [20]:
precovid_tableau = flattened_df_.drop(["ticker_counts", "words"], axis=1)
precovid_tableau

KeyError: "['ticker_counts' 'words'] not found in axis"

In [32]:
precovid_tableau1 = precovid_tableau[~precovid_tableau["keywords"].str.contains("^\d+$")]
precovid_tableau1

,Exchange,tickers,Name,Country,Sector,Industry,text,predicted_label,date,keywords
0,NASDAQ,AAPL,Apple Inc. Common Stock,United States,Technology,Computer Manufacturing,Apple Looking For New High,Positive,10/1/2019,Apple
0,NASDAQ,AAPL,Apple Inc. Common Stock,United States,Technology,Computer Manufacturing,Apple Looking For New High,Positive,10/1/2019,Looking
0,NASDAQ,AAPL,Apple Inc. Common Stock,United States,Technology,Computer Manufacturing,Apple Looking For New High,Positive,10/1/2019,For
0,NASDAQ,AAPL,Apple Inc. Common Stock,United States,Technology,Computer Manufacturing,Apple Looking For New High,Positive,10/1/2019,New
0,NASDAQ,AAPL,Apple Inc. Common Stock,United States,Technology,Computer Manufacturing,Apple Looking For New High,Positive,10/1/2019,High
...,...,...,...,...,...,...,...,...,...,...
6209,NYSE,XOM,Exxon Mobil Corporation Common Stock,United States,Energy,Oil & Gas Production,AGCO CEO explains the impact of coronavirus on...,Neutral,3/31/2020,factories
6209,NYSE,XOM,Exxon Mobil Corporation Common Stock,United States,Energy,Oil & Gas Production,AGCO CEO explains the impact of coronavirus on...,Neutral,3/31/2020,and
6209,NYSE,XOM,Exxon Mobil Corporation Common Stock,United States,Energy,Oil & Gas Production,AGCO CEO explains the impact of coronavirus on...,Neutral,3/31/2020,farm
6209,NYSE,XOM,Exxon Mobil Corporation Common Stock,United States,Energy,Oil & Gas Production,AGCO CEO explains the impact of coronavirus on...,Neutral,3/31/2020,equipment
6209,NYSE,XOM,Exxon Mobil Corporation Common Stock,United States,Energy,Oil & Gas Production,AGCO CEO explains the impact of coronavirus on...,Neutral,3/31/2020,production

In [21]:
stopwords = ["a", "about", "above", "above", "across", "after", "afterwards",
             "again", "against", "all", "almost", "alone", "along", "already", 
             "also","although","always","am","among", "amongst", "amoungst", "amount",  
             "an", "and", "another", "any","anyhow","anyone","anything","anyway", "anywhere", 
             "are", "around", "as",  "at", "back","be","became", "because","become","becomes", 
             "becoming", "been", "before", "beforehand", "behind", "being", "below", "beside", 
             "besides", "between", "beyond", "bill", "both", "bottom","but", "by", "call", 
             "can", "cannot", "cant", "co", "con", "could", "couldnt", "cry", "de", 
             "describe", "detail", "do", "done", "down", "due", "during", "each", "eg", "eight", 
             "either", "eleven","else", "elsewhere", "empty", "enough", "etc", "even", "ever", 
             "every", "everyone", "everything", "everywhere", "except", "few", "fifteen", "fify", 
             "fill", "find", "fire", "first", "five", "for", "former", "formerly", "forty", "found", 
             "four", "from", "front", "full", "further", "get", "give", "go", "had", "has", "hasnt", 
             "have", "he", "hence", "her", "here", "hereafter", "hereby", "herein", "hereupon", "hers", 
             "herself", "him", "himself", "his", "how", "however", "hundred", "ie", "if", "in", "inc", "indeed", "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter", "latterly", "least", "less", "ltd", "made", "many", "may", "me", "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly", "move", "much", "must", "my", "myself", "name", "namely", "neither", "never", "nevertheless", "next", "nine", "no", "nobody", "none", "noone", "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on", "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our", "ours", "ourselves", "out", "over", "own","part", "per", "perhaps", "please", "put", "rather", "re", "same", "see", "seem", "seemed", "seeming", "seems", "serious", "several", "she", "should", "show", "side", "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone", "something", "sometime", "sometimes", "somewhere", "still", "such", "system", "take", "ten", "than", "that", "the", "their", "them", "themselves", "then", "thence", "there", "thereafter", "thereby", "therefore", "therein", "thereupon", "these", "they", "thick", "thin", "third", "this", "those", "though", "three", "through", "throughout", "thru", "thus", "to", "together", "too", "top", "toward", "towards", "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us", "very", "via", "was", "we", "well", "were", "what", "whatever", "when", "whence", "whenever", "where", "whereafter", "whereas", "whereby", "wherein", "whereupon", "wherever", "whether", "which", "while", "whither", "who", "whoever", "whole", "whom", "whose", "why", "will", "with", "within", "without", "would", "yet", "you", "your", "yours", "yourself", "yourselves", "the"]

In [22]:
len(stopwords)

319

In [46]:
precovid_tableau1["keywords"] = precovid_tableau1["keywords"].str.lower()
precovid_tableau1

/Users/abayomi/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,Exchange,tickers,Name,Country,Sector,Industry,text,predicted_label,date,keywords
0,NASDAQ,AAPL,Apple Inc. Common Stock,United States,Technology,Computer Manufacturing,Apple Looking For New High,Positive,10/1/2019,apple
0,NASDAQ,AAPL,Apple Inc. Common Stock,United States,Technology,Computer Manufacturing,Apple Looking For New High,Positive,10/1/2019,looking
0,NASDAQ,AAPL,Apple Inc. Common Stock,United States,Technology,Computer Manufacturing,Apple Looking For New High,Positive,10/1/2019,for
0,NASDAQ,AAPL,Apple Inc. Common Stock,United States,Technology,Computer Manufacturing,Apple Looking For New High,Positive,10/1/2019,new
0,NASDAQ,AAPL,Apple Inc. Common Stock,United States,Technology,Computer Manufacturing,Apple Looking For New High,Positive,10/1/2019,high
...,...,...,...,...,...,...,...,...,...,...
6209,NYSE,XOM,Exxon Mobil Corporation Common Stock,United States,Energy,Oil & Gas Production,AGCO CEO explains the impact of coronavirus on...,Neutral,3/31/2020,factories
6209,NYSE,XOM,Exxon Mobil Corporation Common Stock,United States,Energy,Oil & Gas Production,AGCO CEO explains the impact of coronavirus on...,Neutral,3/31/2020,and
6209,NYSE,XOM,Exxon Mobil Corporation Common Stock,United States,Energy,Oil & Gas Production,AGCO CEO explains the impact of coronavirus on...,Neutral,3/31/2020,farm
6209,NYSE,XOM,Exxon Mobil Corporation Common Stock,United States,Energy,Oil & Gas Production,AGCO CEO explains the impact of coronavirus on...,Neutral,3/31/2020,equipment
6209,NYSE,XOM,Exxon Mobil Corporation Common Stock,United States,Energy,Oil & Gas Production,AGCO CEO explains the impact of coronavirus on...,Neutral,3/31/2020,production

In [47]:
xyz1 = precovid_tableau1[~precovid_tableau1['keywords'].isin(stopwords)]
xyz1

,Exchange,tickers,Name,Country,Sector,Industry,text,predicted_label,date,keywords
0,NASDAQ,AAPL,Apple Inc. Common Stock,United States,Technology,Computer Manufacturing,Apple Looking For New High,Positive,10/1/2019,apple
0,NASDAQ,AAPL,Apple Inc. Common Stock,United States,Technology,Computer Manufacturing,Apple Looking For New High,Positive,10/1/2019,looking
0,NASDAQ,AAPL,Apple Inc. Common Stock,United States,Technology,Computer Manufacturing,Apple Looking For New High,Positive,10/1/2019,new
0,NASDAQ,AAPL,Apple Inc. Common Stock,United States,Technology,Computer Manufacturing,Apple Looking For New High,Positive,10/1/2019,high
1,NASDAQ,AAPL,Apple Inc. Common Stock,United States,Technology,Computer Manufacturing,Huazhu Hotels: 1 Little-Known China Tourism Stock,Positive,10/2/2019,huazhu
...,...,...,...,...,...,...,...,...,...,...
6209,NYSE,XOM,Exxon Mobil Corporation Common Stock,United States,Energy,Oil & Gas Production,AGCO CEO explains the impact of coronavirus on...,Neutral,3/31/2020,coronavirus
6209,NYSE,XOM,Exxon Mobil Corporation Common Stock,United States,Energy,Oil & Gas Production,AGCO CEO explains the impact of coronavirus on...,Neutral,3/31/2020,factories
6209,NYSE,XOM,Exxon Mobil Corporation Common Stock,United States,Energy,Oil & Gas Production,AGCO CEO explains the impact of coronavirus on...,Neutral,3/31/2020,farm
6209,NYSE,XOM,Exxon Mobil Corporation Common Stock,United States,Energy,Oil & Gas Production,AGCO CEO explains the impact of coronavirus on...,Neutral,3/31/2020,equipment
6209,NYSE,XOM,Exxon Mobil Corporation Common Stock,United States,Energy,Oil & Gas Production,AGCO CEO explains the impact of coronavirus on...,Neutral,3/31/2020,production

In [23]:
# Neutral_Text = ""
# Pos_Text = ""
# Neg_Text = ""
# for index, row in merged_df.iterrows():
# #     print(row['predicted_label'])
#     if row['predicted_label'] == "Neutral":
#         Neutral_Text = Neutral_Text+row['text']+' '
#     if row['predicted_label'] == "Positive":
#         Pos_Text = Pos_Text+row['text']+' '
#     if row['predicted_label'] == "Negative":
#         Neg_Text = Neg_Text+row['text']+' '

In [24]:
# Neutral_Text

In [25]:
# # Cleaning text and lower casing all words
# for char in ',$()-?&\'.‘’%:':
#     Neutral_Text=Neutral_Text.replace(char,' ')
# Neutral_Text
# Neutral_Text = Neutral_Text.lower()
# # split returns a list of words delimited by sequences of whitespace (including tabs, newlines, etc, like re's \s) 
# word_list_neutral = Neutral_Text.split()
# neutral_common_words = Counter(word_list_neutral).most_common()
# df_sentiment_neutral = pd.DataFrame(neutral_common_words)
# df_sentiment_neutral['predicted_labels'] = "Neutral"
# # neutral_common_words

In [26]:
# # Cleaning text and lower casing all words
# for char in ',$()-?&\'.‘’%:':
#     Pos_Text=Pos_Text.replace(char,' ')
# Pos_Text = Pos_Text.lower()
# # split returns a list of words delimited by sequences of whitespace (including tabs, newlines, etc, like re's \s) 
# word_list_Pos = Pos_Text.split()
# pos_common_words = Counter(word_list_Pos).most_common()
# df_sentiment_pos = pd.DataFrame(pos_common_words)
# df_sentiment_pos['predicted_labels'] = "Positive"
# df_sentiment_pos

In [27]:
# # Cleaning text and lower casing all words
# for char in ',$()-?&\'.‘’%:':
#     Neg_Text=Pos_Text.replace(char,' ')
# Neg_Text = Neg_Text.lower()
# # split returns a list of words delimited by sequences of whitespace (including tabs, newlines, etc, like re's \s) 
# word_list_Neg = Neg_Text.split()
# neg_common_words = Counter(word_list_Neg).most_common()
# df_sentiment_neg = pd.DataFrame(neg_common_words)
# df_sentiment_neg['predicted_labels'] = "Negative"
# df_sentiment_neg

In [28]:
# df_sentiment_all = df_sentiment_pos.append(df_sentiment_neg)
# df_sentiment_all = df_sentiment_all.append(df_sentiment_neutral)
# df_sentiment_all

In [29]:
# df1 = pd.DataFrame(common_words)

In [30]:
# df_sentiment_all.to_csv("Resources/Tableau_pre_covid_word_count_with_sentiment.csv")